#ifndef LEXGINE_CORE_MISC_BUILD_INFO_H

#define PROJECT_CODE_NAME "LEXGINE ORIGIN"
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_REVISION 0
#define PROJECT_VERSION_STAGE "internal"

#define LEXGINE_CORE_MISC_BUILD_INFO_H
#endif
