#ifndef COMMON_H
#define COMMON_H

#define PI 3.14159265

#define SCENE_DATA_REGISTER    b0
#define OBJECT_DATA_REGISTER   b1
#define MATERIAL_DATA_REGISTER b2

#define SHADER_FUNCTION_SPACE space100

#endif